### ISSUE TITLE
Extends fly.Object

### ISSUE THREAD

**Issue by svantroyen** [rhinofly-cso/DocumentationGenerator#1]
Hello, sorry to create an issue for this but i can't find a way to contact you to ask this : some cfc's extend "fly.Object", but this folder and its objects don't seem to be available in the code? 
Can you please add it or explain how to use it without (ok i could remove the "extends blabla" but maybe it's needed in the further process...)
Thanks in advance!

**Comment by jbrunemann** [comment]
Thanks for the feedback. Very good point! I'll look into it and get back to you.

**Comment by jbrunemann** [comment]
Please do a `pull` and try again, the dependency should now be removed.

**Comment by svantroyen** [comment]
It is removed indeed, thank you very much for your super fast answer :-)
